### ISSUE TITLE
Issue with reusing components twice

### ISSUE THREAD

**Issue by mskorkowski** [AaronErhardt/relm4#25] opened 2021-09-14 03:19 UTC
I've created a fairly complex reusable component which I would like to use twice with different settings in the same view. The way in  which components are initiated makes it hard to select proper configuration of the component.

I've simplified the case and created a gist with example issue and solution I came up with. https://gist.github.com/mskorkowski/ae88013c4d19b6479270aeeaa08e8416

Current state of relm4 makes it hard to reuse components more then once in the widget.

I don't like the solution I've created because
1. It moves configuration of the component away from the creation step (`Components::init_components`)
2. Overly complex and verbose
3. Produces polution in the namespace if component is used many times in application

What I would like to, is 
1. `ComponentUpdate::init_model` to take component settings struct as an argument instead of parent model
2. `RelmComponent::new` had additional argument for component settings struct

**Comment by AaronErhardt** [comment] 2021-09-14 06:37
Thanks for your feedback!
Maybe your solution can be simplified. Generics should work pretty well in this case. I will try it out this afternoon. If that doesn't work we can still use your suggestion.

**Comment by mskorkowski** [comment] 2021-09-14 16:22
I've created a pull request with implementation where the settings are passed alongside the model. In this solution, Model has another dependant type.

```
struct Model {
    type Msg: 'static;
    type Widgets;
    type Components: Components<Self>;
    type Settings;
}
```

https://github.com/AaronErhardt/relm4/pull/26

Things I found nice about this approach is that
1. Every part of application can receive initial configuration in plain way
2. `RelmApp::new` also needs a Settings, which could allow in future setting proper application id for apps using relm as per gtk requirement.

**Comment by AaronErhardt** [comment] 2021-09-14 19:05
Thanks a lot for your effort!

I appreciate your idea, but to be honest, I'm not really convinced by your approach yet. The problem is that adding the `Settings` type to the `Model` trait is only useful for reusable components and nothing else.

Regarding point 1, the model for the app is already initialized from outside and the components have the `init_model` function for exactly this
Regarding point 2, I don't see how that would help with the application id. Also there's this already: https://aaronerhardt.github.io/docs/relm4/relm4/fn.gtk_application.html

I've tried to make the alert component reusable twice or more without changing the relm4 crate. I've added the changes to this branch: https://github.com/AaronErhardt/relm4/tree/reusable-comps
IMO this approach is pretty reasonable and it only required a few extra lines of code both for the component and the application part.

**Comment by mskorkowski** [comment] 2021-09-14 20:05
> Regarding point 1, the model for the app is already initialized from outside and the components have the init_model function for exactly this
👍🏻 

> Regarding point 2, I don't see how that would help with the application id. Also there's this already: https://aaronerhardt.github.io/docs/relm4/relm4/fn.gtk_application.html

I've considered this method a hack to access the gtk app when relm is lacking and was thinking of making Settings provide the missing parts, but this can be done independently or with adding extra constrains over the model passed to `RelmApp::new`.

----

Now going back to the reusing components. Your solution is simpler to implement, so let's follow that. If you like I can upgrade other components with this changes.

**Comment by AaronErhardt** [comment] 2021-09-14 20:17
Btw. I had already prepared a patch for point 2 that allows you to pass a custom app to the RelmApp. I've pushed it now: https://github.com/AaronErhardt/relm4/commit/488bd23e28375ce4447e974f9163e5ca9022a7ae.

If you want to upgrade the other components that'd be awesome :)

**Comment by mskorkowski** [comment] 2021-09-15 04:34
When migrating the components I've hit https://github.com/AaronErhardt/Tracker/issues/2 . Unfortunately I'm too stupid to fix it.

**Comment by AaronErhardt** [comment] 2021-09-15 05:27
I'll try to fix it when I'm back from work in about 10 hours. In the meantime just remove the tracker and use watch! instead. We can always add the tracker later again.

**Comment by AaronErhardt** [comment] 2021-09-15 19:23
I hope the tracker macro now works properly with generics :)

**Comment by mskorkowski** [comment] 2021-09-15 19:43
I've rose PR with changes. Please review and let me know if I should do some updates

**Comment by AaronErhardt** [comment] 2021-10-09 06:03
Fixed with https://github.com/AaronErhardt/relm4/pull/27

**Closed by AaronErhardt** 2021-10-09 06:03 UTC
