### ISSUE TITLE
Support libadwaita's Application or init()

### ISSUE THREAD

**Issue by delight-aug** [AaronErhardt/Relm4#133] opened 2022-03-22 01:21 UTC
Hi! I'm trying to build a libadwaita GTK application. For adwaita styles to be set up for the application, I have to either use [libadwaita::Application](https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/stable/latest/docs/libadwaita/struct.Application.html) or call [init()](https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/stable/latest/docs/libadwaita/functions/fn.init.html#) on application startup.
The first approach doesn't work because [RelmApp::with_app()](https://aaronerhardt.github.io/docs/relm4/relm4/struct.RelmApp.html#method.with_app) only work with `gtk4::Application`. So I've tried the second approach:
```
fn main() {
    let model = app::AppModel;
    let app = gtk::Application::builder()
        .application_id("com.example.App")
        .build();
    app.connect_startup(|_| adw::init());
    let app = RelmApp::with_app(model, app);
    app.run();
}
```

However, it fails on runtime with the following message:
```
thread 'main' panicked at 'GTK has not been initialized. Call `gtk::init` first.', /home/mks/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.7/src/auto/box_.rs:41:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: gtk4::auto::box_::Box::new
             at /home/mks/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.7/src/auto/box_.rs:41:9
   3: <gtk_files::app::AppWidgets as relm4::traits::Widgets<gtk_files::app::AppModel,()>>::init_view
             at ./src/app.rs:27:20
   4: relm4::app::RelmApp<Model>::with_app
             at /home/mks/.cargo/registry/src/github.com-1ecc6299db9ec823/relm4-0.4.3/src/app.rs:71:27
   5: gtk_files::main
             at ./src/main.rs:12:15
   6: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
The terminal process "cargo 'run', '--package', 'gtk-files', '--bin', 'gtk-files'" terminated with exit code: 101.
```

**Comment by AaronErhardt** [comment] 2022-03-22 08:43
Have you tried the "libadwaita" feature flag?

**Comment by delight-aug** [comment] 2022-03-22 09:48
No, I haven't noticed it. Now I've enabled it and changed the code to the following:
```
fn main() {
    let model = app::AppModel;
    let app = adw::Application::builder()
        .application_id("com.example.App")
        .build();
    let app = RelmApp::with_app(model, app);
    app.run();
}

```
But it didn't change anything, the backtrace is the same. I also tried deleting `Cargo.lock` and running `cargo clean`. [Example libadwaita application](https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/stable/latest/docs/libadwaita/index.html#example) runs just fine, tho. Both with gtk and adw Application.

Backtrace:
```
thread 'main' panicked at 'GTK has not been initialized. Call `gtk::init` first.', /home/mks/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.7/src/auto/box_.rs:41:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: gtk4::auto::box_::Box::new
             at /home/mks/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.7/src/auto/box_.rs:41:9
   3: <gtk_files::app::AppWidgets as relm4::traits::Widgets<gtk_files::app::AppModel,()>>::init_view
             at ./src/app.rs:27:20
   4: relm4::app::RelmApp<Model>::with_app
             at /home/mks/.cargo/registry/src/github.com-1ecc6299db9ec823/relm4-0.4.3/src/app.rs:71:27
   5: gtk_files::main
             at ./src/main.rs:11:15
   6: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by AaronErhardt** [comment] 2022-03-22 10:25
The backtrace says the panic was caused by

```
   4: relm4::app::RelmApp<Model>::with_app
             at /home/mks/.cargo/registry/src/github.com-1ecc6299db9ec823/relm4-0.4.3/src/app.rs:71:27
```

Can you show me the code at this line?

**Comment by delight-aug** [comment] 2022-03-22 12:39
Sure. The column number is a bit off, but it's indeed crashing on line 27, the first line in `init_view`, `let vbox = gtk::Box::new(gtk::Orientation::Vertical, 0);` . Here is the full `app.rs` module;
```
use gtk::traits::BoxExt;
use relm4::{AppUpdate, Model, Widgets};

pub struct AppModel;
impl Model for AppModel {
    type Msg = ();
    type Widgets = AppWidgets;
    type Components = ();
}

impl AppUpdate for AppModel {
    fn update(
        &mut self,
        _msg: Self::Msg,
        _components: &Self::Components,
        _sender: relm4::Sender<Self::Msg>,
    ) -> bool {
        true
    }
}

pub struct AppWidgets(adw::ApplicationWindow);
impl Widgets<AppModel, ()> for AppWidgets {
    type Root = adw::ApplicationWindow;

    fn init_view(_model: &AppModel, _components: &(), _sender: relm4::Sender<()>) -> Self {
        let vbox = gtk::Box::new(gtk::Orientation::Vertical, 0);
        vbox.append(
            &adw::HeaderBar::builder()
                .title_widget(&adw::WindowTitle::new("Demo App", ""))
                .build(),
        );

        Self(
            adw::ApplicationWindow::builder()
                .default_width(350)
                .default_height(100)
                .content(&vbox)
                .build(),
        )
    }

    fn root_widget(&self) -> Self::Root {
        self.0.clone()
    }

    fn view(&mut self, _model: &AppModel, _sender: relm4::Sender<()>) {}
}
```
This is the whole app now. Just connect this module to main.rs.

P.S. Turns out, this code works just fine with `RelmApp::new(model)`, and has adwaita styles if the `libadwaita` feature is enabled.

![Screenshot from 2022-03-22 14-38-40](https://user-images.githubusercontent.com/51861383/159483813-61f30b6d-2523-4b29-bd39-bf8cdbb232a1.png)

**Comment by AaronErhardt** [comment] 2022-03-22 12:50
I've just pushed a fix for the initialization. Can you try with the latest code from git?

**Comment by delight-aug** [comment] 2022-03-22 13:14
This time it's the following backtrace:
```
thread 'main' panicked at 'Gtk has to be initialized before using libadwaita.', /home/mks/.cargo/registry/src/github.com-1ecc6299db9ec823/libadwaita-0.1.1/src/auto/functions.rs:43:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:525:12
   1: libadwaita::auto::functions::init
             at /home/mks/.cargo/registry/src/github.com-1ecc6299db9ec823/libadwaita-0.1.1/src/auto/functions.rs:43:5
   2: relm4::app::RelmApp<Model>::with_app
             at /home/mks/.cargo/git/checkouts/relm4-2fc0f2271e83be1c/9be5a93/src/app.rs:71:9
   3: gtk_files::main
             at ./src/main.rs:10:15
   4: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
```

Then, I've modified the `init` function you introduced, like so:
```

fn init() {
    gtk::init().expect("Couldn't initialize GTK");

    #[cfg(feature = "libadwaita")]
    adw::init();
}

```
And it worked!

![Screenshot from 2022-03-22 15-12-06](https://user-images.githubusercontent.com/51861383/159489940-6095f98f-1288-4e0b-beb2-da772da51035.png)

**Comment by delight-aug** [comment] 2022-03-22 14:18
I would like to send a PR once I return from a shelter (today, probably soon). Thank you for helping out!

**Closed** 2022-03-22 18:03 UTC
