### ISSUE TITLE
relm4_macros: view needs parentheses for basic equality statements

### ISSUE THREAD

**Issue by Absolucy** [AaronErhardt/Relm4#109] opened 2022-02-15 23:06 UTC
This is an annoying quirk in `relm4_macros::view!`, which is easier to explain with examples.

This does not work:
```rs
#[derive(PartialEq, Eq)]
enum ExampleEnum {
	A,
	B
}

fn example(value: ExampleEnum) -> gtk4::CheckButton {
	view! {
		checkbox = gtk4::CheckButton {
			set_active: value == ExampleEnum::A
		}
	}
	checkbox
}
```
It errors like this:
```
error: expected identifier
  --> applets/cosmic-applet-graphics/src/main.rs:99:54
   |
99 |                         set_active: current_graphics == Graphics::Integrated,
   |
```

However, if you add parentheses around it, it works fine:
```rs
#![allow(unused_parens, clippy::double_parens)] // needed for a quirk in the view! macro

#[derive(PartialEq, Eq)]
enum ExampleEnum {
	A,
	B
}

fn example(value: ExampleEnum) -> gtk4::CheckButton {
	view! {
		checkbox = gtk4::CheckButton {
			set_active: (value == ExampleEnum::A)
		}
	}
	checkbox
}
```

This, while it doesn't impact functionality, is rather annoying to have deal with, especially disabling otherwise useful lints to avoid getting warnings.

**Comment by Absolucy** [comment] 2022-02-15 23:07
Wait I pressed enter too early, whoops.

**Comment by AaronErhardt** [comment] 2022-02-16 07:21
Thanks for letting me know. I this is caused by the macro thinking that
`ident: name = ...` is followed by a widget initialisation. 
I will send a fix as soon as I have time for it.

**Comment by AaronErhardt** [comment] 2022-02-17 17:19
Should be fixed on git now. Could you try if that works for you?

**Closed** 2022-03-03 12:22 UTC
