### ISSUE TITLE
relm4-components fails to build

### ISSUE THREAD

**Issue by mskorkowski** [AaronErhardt/relm4#36] opened 2021-10-02 23:02 UTC
When I build the master branch I receive an error in `alert` component that `default` is undefined in `MessageDialog`

```
no function or associated item named `default` found for struct `MessageDialog` in the current scope
```

Expanded `AlertWidgets`

```rust
    /// Widgets of the alert component
    pub struct AlertWidgets {
        #[allow(missing_docs)]
        pub dialog: gtk::MessageDialog,
    }
    impl<ParentModel, Conf> relm4::Widgets<AlertModel<Conf>, ParentModel> for AlertWidgets
    where
        ParentModel: AlertParent,
        ParentModel::Widgets: ParentWindow,
        Conf: AlertConfig,
    {
        type Root = gtk::MessageDialog;
        /// Initialize the UI.
        fn init_view(
            model: &AlertModel<Conf>,
            parent_widgets: &<ParentModel as ::relm4::Model>::Widgets,
            sender: ::gtk::glib::Sender<<AlertModel<Conf> as ::relm4::Model>::Msg>,
        ) -> Self {
            let dialog = gtk::MessageDialog::default();
            dialog.set_transient_for(parent_widgets.parent_window().as_ref());
            dialog.set_message_type(gtk::MessageType::Question);
            dialog.set_visible(model.is_active);
            dialog.set_text(Some(model.settings.text));
            dialog.set_secondary_text(model.settings.secondary_text.as_deref());
            dialog.set_modal(model.settings.is_modal);
            dialog.add_button(model.settings.confirm_label, gtk::ResponseType::Accept);
            dialog.add_button(model.settings.cancel_label, gtk::ResponseType::Cancel);
            {
                #[allow(clippy::redundant_clone)]
                let sender = sender.clone();
                dialog.connect_response(move |_, response| {
                    sender
                        .send(AlertMsg::Response(response))
                        .expect("Receiver was dropped!");
                });
            }
            if let Some(option_label) = &model.settings.option_label {
                dialog.add_button(option_label, gtk::ResponseType::Other(0));
            }
            if model.settings.destructive_accept {
                let accept_widget = dialog
                    .widget_for_response(gtk::ResponseType::Accept)
                    .expect("No button for accept response set");
                accept_widget.add_css_class("destructive-action");
            }
            Self { dialog }
        }
        fn connect_components(
            &self,
            model: &AlertModel<Conf>,
            components: &<AlertModel<Conf> as ::relm4::Model>::Components,
        ) {
        }
        /// Return the root widget.
        fn root_widget(&self) -> Self::Root {
            self.dialog.clone()
        }
        /// Update the view to represent the updated model.
        fn view(
            &mut self,
            model: &AlertModel<Conf>,
            sender: ::gtk::glib::Sender<<AlertModel<Conf> as ::relm4::Model>::Msg>,
        ) {
            self.dialog.set_visible(model.is_active);
        }
    }
}
```

Only `default` being called is in the first line of `init_view`. As gtk-rs docs indicate MessageDialog doens't have `default` method.

**Comment by AaronErhardt** [comment] 2021-10-03 09:33
Yes that's unfortunate and I'm tired of failing CI mails, but because all default widget implementations were moved to gtk4-rs I can't  improve this situation myself. I've done everything in my power to get this working and even pointed out that a point release would be important for Relm4: https://github.com/gtk-rs/gtk4-rs/pull/595

If you want, I can write a temporary fix and remove the changes as soon someone at gtk4-rs merges my PR.

**Comment by emmanueltouzery** [comment] 2021-10-03 13:15
Sorry if I misunderstand the issue, but it seems to me that you could depend on a git commit of gtk:
https://stackoverflow.com/a/54197014/516188

Maybe you were not aware of that cargo feature?

**Comment by mskorkowski** [comment] 2021-10-03 13:22
If we are waiting for gtk-rs, let's wait. I'll just 🙈 while doing my macro update.

I think next time would be better to wait for gtk-rs to merge PR before making master broken. Additionally can you add `gtk-rs label to this issue.
----
@emmanueltouzery 

I'm aware. I think Aaron Erhardt is also aware. From my point of view it's not a sane behavior to do that while you develop library. 

Your library is then consumed by other libs and applications, and what you consider a non breaking change can break a lots of code for others since you can't give guarantees on the changes done by the gtk-rs.

**Comment by AaronErhardt** [comment] 2021-10-03 13:23
@emmanueltouzery yes, but the problem is that `libadwaita` wants to have gtk4-rs from crates.io. This causes cargo to fail package resolution...

**Comment by AaronErhardt** [comment] 2021-10-03 13:25
@mskorkowski I know that master shouldn't be broken. I expected the transition to be faster and it's unfortunately that a single type now causes this problem. I think I will post a workaround so you and everyone else can continue until gtk-rs merges my PR and adds a point release.

**Comment by AaronErhardt** [comment] 2021-10-09 06:02
Fixed with https://github.com/gtk-rs/gtk4-rs/pull/595

**Closed by AaronErhardt** 2021-10-09 06:02 UTC
Labels: gtk-rs

**Comment by uvizhe** [comment] 2022-05-12 12:39
I'm having this issue with `ShortcutsWindow`,`ShortcutsSection`,`ShortcutsGroup` and `ShortcutsShortcut`.

**Comment by AaronErhardt** [comment] 2022-05-12 21:18
@uvizhe This is not an issue caused by Relm4. Relm4 just uses `gtk::Box::default()` for example if you create a widget by using only the type definition (`gtk::Box`). You can still use `gtk::Box::new(...)` to initialize your widget with a specific constructor. Sadly, the whole shortcuts stuff is only tailored towards use of .ui files with gtk::Builder. This makes it particularly hard to use in Relm4 and basically impossible to use in the `view!` macro.

I would love to improve the current situation, but I don't have a good idea yet. First of all, it must be possible to create a shortcuts window in pure gtk-rs code and then we can think about improving the macro. Menus already have a special `menu!` macro, maybe we can have something similar for shortcuts.
