### ISSUE TITLE
Ordering issues when using ":" and "=" with the same operation in view macro

### ISSUE THREAD

**Issue by cofee-on-the-desk** [AaronErhardt/Relm4#87] opened 2022-01-27 11:59 UTC
Look at this example: 

```rust
#[relm4::widget]
impl Widgets<AppModel, ()> for AppWidgets {
    fn pre_init() {
        relm4::view! {
            gtk_box = gtk::Box {
                set_orientation: gtk::Orientation::Vertical,
                append: &gtk::Label::new(Some("A")),
                append = &gtk::Label {
                    set_label: "B",
                },
                append: &gtk::Label::new(Some("C")),
                inline_css: b"background-color:red",
            }
        }
    }
    view! {
        window = gtk::ApplicationWindow {
            set_child = Some(&gtk::Box) {
                set_orientation: gtk::Orientation::Horizontal,
                append: &gtk_box,
                append = &gtk::Box {
                    set_orientation: gtk::Orientation::Vertical,
                    append: &gtk::Label::new(Some("A")),
                    append = &gtk::Label {
                        set_label: "B",
                    },
                    append: &gtk::Label::new(Some("C")),
                    inline_css: b"background-color:blue",
                },
            }
        }
    }
}
```

In the view macro, we combine ":" and "=" to append labels to the boxes, and to append boxes to the main window box.

Note that boxes are created with the same code, just in different places:

Red box - created in pre_init, added with ":"
```rust
relm4::view! {
    gtk_box = gtk::Box {
        set_orientation: gtk::Orientation::Vertical,
	append: &gtk::Label::new(Some("A")),
	append = &gtk::Label {
            set_label: "B",
	},
	append: &gtk::Label::new(Some("C")),
	inline_css: b"background-color:red",
    }
}
```

Blue box
 - created/added in place with "="
```rust
append = &gtk::Box {
    set_orientation: gtk::Orientation::Vertical,
    append: &gtk::Label::new(Some("A")),
    append = &gtk::Label {
        set_label: "B",
    },
    append: &gtk::Label::new(Some("C")),
    inline_css: b"background-color:blue",
},			
```

The results:

![order](https://user-images.githubusercontent.com/89153225/151353804-8726cb6e-91ec-4525-9bd5-c5c2217374fb.png)

The order of elements isn't something I expect, when I look at the code:

1) I expect the box order to be red->blue, not the opposite.
2) I expect the label order to be A->B->C, not B->A->C or A->C->B.
3) As the boxes were created with the same code, I expect them to have the same order of children.

Although I'm not sure if combining ":" and "=" is something you would want to do in an application, it's still a bit confusing.

**Comment by AaronErhardt** [comment] 2022-01-27 13:34
The macro currently distinguishes between `:` and `=` and generates the code in separate streams, which causes your ordering issue. The reason for this is historic and it's not necessary anymore in 0.4.

I will fix this as soon as I have time for it (probably this weekend). I hope in the meantime you can use something like prepend to work around this issue.

Thanks for letting me know!

**Comment by AaronErhardt** [comment] 2022-01-28 20:10
I've added a commit that should fix the issue. Can you test the latest version of Relm4 from git and tell me if this works for you?

**Comment by cofee-on-the-desk** [comment] 2022-01-29 07:27
Tried it. Works flawlessly for my box example and some other situations I've been testing, including the ones with `iterate!` and `factory!`.

A small note though:

```rust
use relm4::{gtk, view};
fn main() {
    view! {
        mut vec = Vec::new() {
            push: gtk::Label::new(Some("5")),
            push = gtk::Label {
                set_label: "6",
            }
        }
    }
    println!("{vec:#?}");
}
```

This won't compile:

```rust
error[E0382]: borrow of moved value: `_gtk_label_0`
  --> src\main.rs:12:20
   |
12 |               push = gtk::Label {
   |                      ^--
   |                      |
   |                      value moved here
   |  ____________________move occurs because `_gtk_label_0` has type `relm4::gtk4::Label`, which does not implement the `Copy` trait
   | |
13 | |                 set_label: "6",
   | |_________________________^ value borrowed here after move

```

The label is moved into the vector before we can edit it.

As far as I can tell, this issue doesn't happen with gtk widgets, as all of their methods take shared references of the child widgets. So it's more like a rare edge case, and not something you should care about too much. Nevertheless, it's something I wanted to share.

And thanks for your work on relm4. I'm using it for a small project at university and I'm really enjoying it.

**Comment by AaronErhardt** [comment] 2022-01-31 09:16
Ok, so the second issue is caused by the ordering of streams again. I think the stream that connects the widgets (does the assignment, in this case the `push`) comes before the initialization (in this case `set_label`). It usually doesn't matter for widget because they are passed by reference but for `Vec` that's bad, obviously. I think changing the order makes sense, I will try to push a patch this evening.

**Comment by AaronErhardt** [comment] 2022-02-02 21:28
@cofee-on-the-desk I've pushed another patch that should fix your second issue. I've also added your example to relm4-examples so it is picked up by the CI in case there should be a regression.

Can you try it out? If it works for you I will publish another point release.

**Comment by cofee-on-the-desk** [comment] 2022-02-03 08:09
@AaronErhardt Works fine.

**Comment by AaronErhardt** [comment] 2022-02-04 13:11
Should be fixed now with the latest point release.

**Closed by AaronErhardt** 2022-02-04 13:11 UTC
Labels: fixed-with-next-release
